[package]
name = "loss72-platemaker-core"
version = "0.1.0"
edition = "2024"

[dependencies]
loss72-platemaker-widgets = { version = "0.1.0", path = "../widgets" }
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
